## Section A:Data Structures & Control Structures

In [33]:
#1
list1=[45,65,88,6,22]
list1.append(47)
list1

[45, 65, 88, 6, 22, 47]

In [34]:
list1.extend([72,54])
list1

[45, 65, 88, 6, 22, 47, 72, 54]

In [35]:
list1.insert(3,19)
list1

[45, 65, 88, 19, 6, 22, 47, 72, 54]

In [36]:
list1.remove(6)
list1

[45, 65, 88, 19, 22, 47, 72, 54]

In [37]:
list1.pop()
list1

[45, 65, 88, 19, 22, 47, 72]

In [38]:
list1.index(19)

3

In [39]:
list1.insert(4,22)
list1.count(22)

2

In [40]:
list1.sort()
list1

[19, 22, 22, 45, 47, 65, 72, 88]

In [41]:
list1.reverse()
list1

[88, 72, 65, 47, 45, 22, 22, 19]

In [42]:
list1.clear()
list1

[]

In [43]:
#2
tup1=("Gowtham","Raju","Sai")
tup1

('Gowtham', 'Raju', 'Sai')

Tuple is immutable.we cannot change the tuple once it is created.There is only two funtions that can be done on the tuple.They are count and index.So, second name in the name cannot be changed

In [44]:
#3
set1={12,54,14,66,78,12}
set1

{12, 14, 54, 66, 78}

The set cannot print the duplicates.It will remove the duplicates in the set.It only prints the unqiue values.And also the it ordered the unordered data

In [45]:
#4
dict1={"name":"Gowtham","age":22,"city1":"vijayawada"}
dict1

{'name': 'Gowtham', 'age': 22, 'city1': 'vijayawada'}

In [46]:
dict1.update(age=21)
dict1

{'name': 'Gowtham', 'age': 21, 'city1': 'vijayawada'}

In [47]:
dict1.setdefault("email","gowtham@gamil.com")
dict1

{'name': 'Gowtham',
 'age': 21,
 'city1': 'vijayawada',
 'email': 'gowtham@gamil.com'}

In [48]:
#5
age=int(input("Enter your age"))
if age>=18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter your age 54


You are eligible to vote


In [49]:
#6
marks=int(input("Enter the marks"))
if marks >= 90:
    print("Your grade is:A")
elif marks >=75 and marks<=89:
    print("Your grade is:B")
elif marks >=50 and marks <=74:
    print("Your grade is:c")
else:
    print("You are failed in the exam")

Enter the marks 45


You are failed in the exam


In [50]:
#### 7
num=int(input("Enter a number"))
if num>0:
    if num%2==0:
        print("It's both positive and even")
    else:
        print("It's both positive and not even")
    
elif num==0:
    print("0")
else:
    print("it is negative")

Enter a number 5


It's both positive and not even


## Section B: Numpy

In [64]:
#8
import numpy as np
one=np.array(5)
one

array(5)

In [65]:
oned=np.array([1,2,3,4,5])
oned

array([1, 2, 3, 4, 5])

In [66]:
twod=np.array([[10,20,30],[40,50,60]])
twod

array([[10, 20, 30],
       [40, 50, 60]])

In [67]:
#9
random=np.random.randint(0,100,size=(4,4))
random

array([[11, 47, 55, 20],
       [89, 78,  3, 14],
       [11, 24, 50, 72],
       [ 5, 69, 63, 98]], dtype=int32)

In [68]:
#10
import pandas as pd
two=np.array([[10,20,30],[40,50,60],[70,80,90]])
two

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [69]:
pan=pd.DataFrame(two,columns=["A","B","C"])
pan

A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

## Section C: Exploring Pandas

In [70]:
dict1={
    "Name":["Gowtham","Raju","Raza","sai","sai","Vinay","siva","kumar","rishi","anil","siddhu"],
    "Age":[21,22,21,20,20,22,24,25,27,31,28],
    "City":["Vijayawada","Hyderbad","Chennai","Vijayawada","Vijayawada","Hyderbad","Chennai","Vijayawada","Hyderbad","Chennai","vizag"],
    "Salary":[25000,30000,45000,25000,25000,20000,30000,45000,np.nan,50000,55000]
}
sal=pd.DataFrame(dict1,index=[1,2,3,4,5,6,7,8,9,10,11])
sal

Name  Age        City   Salary
1   Gowtham   21  Vijayawada  25000.0
2      Raju   22    Hyderbad  30000.0
3      Raza   21     Chennai  45000.0
4       sai   20  Vijayawada  25000.0
5       sai   20  Vijayawada  25000.0
6     Vinay   22    Hyderbad  20000.0
7      siva   24     Chennai  30000.0
8     kumar   25  Vijayawada  45000.0
9     rishi   27    Hyderbad      NaN
10     anil   31     Chennai  50000.0
11   siddhu   28       vizag  55000.0

In [71]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 1 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 440.0+ bytes


In [72]:
sal.describe()

Age        Salary
count  11.000000     10.000000
mean   23.727273  35000.000000
std     3.635682  12472.191289
min    20.000000  20000.000000
25%    21.000000  25000.000000
50%    22.000000  30000.000000
75%    26.000000  45000.000000
max    31.000000  55000.000000

In [73]:
sal[["Name","City"]]

Name        City
1   Gowtham  Vijayawada
2      Raju    Hyderbad
3      Raza     Chennai
4       sai  Vijayawada
5       sai  Vijayawada
6     Vinay    Hyderbad
7      siva     Chennai
8     kumar  Vijayawada
9     rishi    Hyderbad
10     anil     Chennai
11   siddhu       vizag

In [74]:
sal.drop("City",axis=1)

Name  Age   Salary
1   Gowtham   21  25000.0
2      Raju   22  30000.0
3      Raza   21  45000.0
4       sai   20  25000.0
5       sai   20  25000.0
6     Vinay   22  20000.0
7      siva   24  30000.0
8     kumar   25  45000.0
9     rishi   27      NaN
10     anil   31  50000.0
11   siddhu   28  55000.0

In [75]:
sal["Salary"].fillna(sal["Salary"].mean(),inplace=True)
sal

C:\Users\gandu\AppData\Local\Temp\ipykernel_5336\2672281675.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sal["Salary"].fillna(sal["Salary"].mean(),inplace=True)


Name  Age        City   Salary
1   Gowtham   21  Vijayawada  25000.0
2      Raju   22    Hyderbad  30000.0
3      Raza   21     Chennai  45000.0
4       sai   20  Vijayawada  25000.0
5       sai   20  Vijayawada  25000.0
6     Vinay   22    Hyderbad  20000.0
7      siva   24     Chennai  30000.0
8     kumar   25  Vijayawada  45000.0
9     rishi   27    Hyderbad  35000.0
10     anil   31     Chennai  50000.0
11   siddhu   28       vizag  55000.0

In [77]:
drop=sal.drop_duplicates()
drop

Name  Age        City   Salary
1   Gowtham   21  Vijayawada  25000.0
2      Raju   22    Hyderbad  30000.0
3      Raza   21     Chennai  45000.0
4       sai   20  Vijayawada  25000.0
6     Vinay   22    Hyderbad  20000.0
7      siva   24     Chennai  30000.0
8     kumar   25  Vijayawada  45000.0
9     rishi   27    Hyderbad  35000.0
10     anil   31     Chennai  50000.0
11   siddhu   28       vizag  55000.0